### ISSUE TITLE
Fix meta tags

### ISSUE THREAD

**Issue by ajfisher** [ajfisher/ajfisher.me#40]
Update the production of the meta tags to:

- [x] Unfurl properly in slack
- [x] Add images conditionally depending on what type of page they are
- [x] resolve duplicate meta tag issue
